# Generated by Django 6.0.5 on 2026-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_avg',
            field=models.FloatField(default=0.0, verbose_name='Средний рейтинг'),
        ),
    ]
