# Generated by Django 5.2.14 on 2026-05-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код для привязки'),
        ),
    ]
