# Generated by Django 5.2.14 on 2026-05-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_telegram_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
    ]
