# Generated by Django 6.0.5 on 2026-05-22 11:19

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_statusevent_event_city_event_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.event_photo_path, verbose_name='Изображение события'),
        ),
    ]
