# Generated by Django 5.2.14 on 2026-05-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_response'),
        ('ads', '0003_response'),
    ]

    operations = [
    ]
