# Generated by Django 5.2.14 on 2026-05-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_merge_0002_advertisement_response_0003_response'),
        ('ads', '0004_notification'),
    ]

    operations = [
    ]
