# Generated by Django 5.2.14 on 2026-05-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_advertisement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
    ]
