# Generated by Django 6.0.5 on 2026-05-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_merge_20260527_1416'),
        ('ads', '0007_remove_advertisement_image'),
    ]

    operations = [
    ]
